Repository FindBestPractice/TodoList, pull requests merged in 2022-10, with the labels that each got.

#1 refactor: Best Practice를 위한 코드 리팩토링
  package-lock.json
  package.json
  src/components/auth/Form.jsx
  src/components/todolist/List.jsx
  src/components/todolist/Todo.jsx
  src/components/todolist/TodoForm.jsx
  src/components/todolist/TodoListFrame.jsx
  src/components/todolist/UpdateTodo.jsx
  src/elements/Button.jsx
  src/elements/ErrMsg.jsx
  src/elements/Input.jsx
  src/hooks/useInput.js
  src/routers/PrivateRouter.jsx
  src/routers/PublicRouter.jsx
  src/shared/axios.jsx
  yarn.lock
Labels: enhancement

#3 refactor(todo): Todo 기능 관련 리팩토링 진행 및 코드 개선
  .gitignore
  src/components/auth/Form.jsx
  src/components/shared/Footer.jsx
  src/components/shared/Layout.jsx
  src/components/todo/CreateTodo.jsx
  src/components/todo/TodoContainer.jsx
  src/components/todo/todolist/ReadTodo.jsx
  src/components/todo/todolist/Todo.jsx
  src/components/todo/todolist/TodoList.jsx
  src/components/todo/todolist/UpdateTodo.jsx
  src/components/todolist/List.jsx
  src/components/todolist/Lists.jsx
  src/pages/NotFound.jsx
  src/pages/TodoList.jsx
  src/shared/axios.jsx
Labels: refactor

#6 docs(pr): 팀업 환경 구축을 위한 PR 템플릿 작성
  .github/pull_request_template.md
Labels: documentation

#8 feat(element): input 엘리먼트 추가
  src/components/auth/Form.jsx
  src/components/todo/CreateTodo.jsx
  src/components/todo/todolist/UpdateTodo.jsx
  src/elements/Input.jsx
  yarn.lock
Labels: enhancement

#7 feat(axios): axios interceptors 함수형으로 변경, 조건문 수정
  src/shared/axios.jsx
Labels: enhancement, refactor

#4 feat(element): error 엘리먼트 추가
  src/components/auth/Form.jsx
  src/elements/ErrMsg.jsx
Labels: enhancement

#9 feat(element): button 엘리먼트 추가 및 교체
  src/components/auth/Form.jsx
  src/components/todo/CreateTodo.jsx
  src/components/todo/todolist/ReadTodo.jsx
  src/components/todo/todolist/UpdateTodo.jsx
  src/elements/Button.jsx
Labels: enhancement, refactor

#10 readme: readme 템플릿 추가
  README.md
Labels: documentation

#11 refactor(UpdateTodo): 버튼 text 수정
  src/components/todo/todolist/UpdateTodo.jsx
Labels: refactor

#12 feat(element): input 엘리먼트 수정
  src/components/auth/Form.jsx
  src/components/todo/CreateTodo.jsx
  src/components/todo/todolist/UpdateTodo.jsx
  src/elements/Input.jsx
Labels: enhancement

#13 fix(package.json): conflict 해결
  package-lock.json
Labels: bug

#14 refactor(axios): server 에러 처리 axios에 alert으로 변경
  src/components/auth/Form.jsx
  src/elements/ErrMsg.jsx
  src/shared/axios.jsx
Labels: refactor

#17 docs(README.md): readme 내용 추가
  README.md
Labels: documentation
